services:

  _defaults:
    autowire: true
    autoconfigure: true

  Jaunas\Chip8\:
    resource: 'src/*'

  Symfony\Component\Console\Application:
    class: Symfony\Component\Console\Application
    public: true
    calls:
      - [add, ['@Jaunas\Chip8\Command\Run']]
      - [add, ['@Jaunas\Chip8\Command\Test']]

  Jaunas\Chip8\Work\Worker\:
    resource: 'src/Work/Worker/*'
    tags: { name: 'dispatcher.worker' }
